
var CategoryConstants = {
	CATEGORIES_RECEIVED: "CATEGORIES_RECEIVED",
	FOLLOWED_CATEGORIES_RECEIVED: "FOLLOWED_CATEGORIES_RECEIVED",
	REMOVE_FOLLOWED_CATEGORY: "REMOVE_FOLLOWED_CATEGORY",
	FOLLOWED_CATEGORY_RECEIVED: "FOLLOWED_CATEGORY_RECEIVED"
};

module.exports = CategoryConstants;