
var CategoryConstants = {
	CATEGORIES_RECEIVED: "CATEGORIES_RECEIVED",
	FOLLOWED_CATEGORIES_RECEIVED: "FOLLOWED_CATEGORIES_RECEIVED",
	REMOVE_FOLLOWED_CATEGORIES: "REMOVE_FOLLOWED_CATEGORIES",
	NEW_FOLLOWED_CATEGORIES_RECEIVED: "NEW_FOLLOWED_CATEGORIES_RECEIVED"
};

module.exports = CategoryConstants;