
var RecipeConstants = {
	RECIPES_RECEIVED: "RECIPES_RECEIVED",
	RECIPE_RECEIVED: "RECIPE_RECEIVED",
	PINNED_RECIPES_RECEIVED: "PINNED_RECIPES_RECEIVED",
	RECEIVE_FILTERED_RECIPES: "RECEIVE_FILTERED_RECIPES"
};

module.exports = RecipeConstants;